"""Generate IEC 61131-3 Structured Text (CASE-FSM) files per PLC."""

from __future__ import annotations

import json
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path


def _iec_ident(name: str) -> str:
    """Return a valid IEC 61131-3 identifier for *name*.

    IEC 61131-3 identifiers must start with a letter or underscore.
    If *name* starts with a digit, prefix with ``v_``.
    The logical name (used in the manifest) is unchanged.
    """
    return f"v_{name}" if name and name[0].isdigit() else name

from .model import (
    Control,
    Manifest,
    MultiStateActuatorError,
    Network,
    Plc,
)


def emit(
    network: Network,
    plcs: list[Plc],
    out_dir: str | Path,
    topology: str,
    write_manifest: bool = True,
    inp_filename: str = "",
    plcs_filename: str = "",
) -> Manifest:
    """Emit one .st file per PLC and (optionally) a manifest.

    Returns the Manifest dataclass.
    """
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    sensor_owner = _build_sensor_owner_index(plcs)
    controls_by_link = _index_controls_by_link(network.controls)

    plc_entries: list[dict] = []
    for plc in plcs:
        file_name = f"{topology}_{plc.name.lower()}.st"
        content, fsms, sensors_referenced = _render_plc(
            plc, controls_by_link, sensor_owner, topology, inp_filename, plcs_filename
        )
        (out / file_name).write_text(content, encoding="utf-8")
        plc_entries.append(
            {
                "name": plc.name,
                "file": file_name,
                "actuators": list(plc.actuators),
                "sensors_referenced": sensors_referenced,
                "fsms": fsms,
            }
        )

    manifest = Manifest(
        topology=topology,
        inp=inp_filename,
        plcs_yaml=plcs_filename,
        generated_at=datetime.now(timezone.utc).isoformat(timespec="seconds"),
        plcs=plc_entries,
    )
    if write_manifest:
        (out / f"{topology}_manifest.json").write_text(
            json.dumps(_manifest_to_dict(manifest), indent=2) + "\n",
            encoding="utf-8",
        )
    return manifest


def _manifest_to_dict(m: Manifest) -> dict:
    return {
        "topology": m.topology,
        "inp": m.inp,
        "plcs_yaml": m.plcs_yaml,
        "generated_at": m.generated_at,
        "plcs": m.plcs,
    }


def _build_sensor_owner_index(plcs: list[Plc]) -> dict[str, str]:
    """Map sensor_id -> owning PLC name. Last wins if duplicated (yaml shouldn't)."""
    owner: dict[str, str] = {}
    for plc in plcs:
        for s in plc.sensors:
            owner[s] = plc.name
    return owner


def _index_controls_by_link(controls: list[Control]) -> dict[str, list[Control]]:
    by: dict[str, list[Control]] = defaultdict(list)
    for c in controls:
        by[c.link_id].append(c)
    return by


def _render_plc(
    plc: Plc,
    controls_by_link: dict[str, list[Control]],
    sensor_owner: dict[str, str],
    topology: str,
    inp_filename: str = "",
    plcs_filename: str = "",
) -> tuple[str, list[dict], list[dict]]:
    """Return (file_text, fsms_meta, sensors_referenced_meta)."""
    case_blocks: list[str] = []
    state_var_decls: list[str] = []
    output_decls: list[str] = []
    sensors_used: list[str] = []
    fsms: list[dict] = []

    for act in plc.actuators:
        ctrls = controls_by_link.get(act, [])
        if not ctrls:
            continue  # empty-shell handled in Task 8
        block, fsm_meta, sensors_in_block = _render_case_block(act, ctrls)
        case_blocks.append(block)
        act_id = _iec_ident(act)
        state_var_decls.append(f"    {act_id}_State : INT := 0;")
        output_decls.append(f"    {act_id} : BOOL;")
        sensors_used.extend(sensors_in_block)
        fsms.append(fsm_meta)

    # Unique-preserving order for sensors_used
    seen: set[str] = set()
    sensors_ordered: list[str] = []
    for s in sensors_used:
        if s not in seen:
            seen.add(s)
            sensors_ordered.append(s)

    var_input_lines = [
        _render_var_input_line(s, sensor_owner, plc.name) for s in sensors_ordered
    ]

    sensors_referenced = [
        {"id": s, "owner_plc": sensor_owner.get(s, "")} for s in sensors_ordered
    ]

    if not case_blocks:
        return (
            f"(* Auto-generated by st_gen from {inp_filename} + {plcs_filename}\n"
            f"   Topology: {topology}   PLC: {plc.name}\n"
            f"   DO NOT EDIT. *)\n\n"
            f"PROGRAM {plc.name}\n"
            f"(* No actuators with [CONTROLS] entries -- sensor-only or "
            f"static-setting PLC. *)\n"
            f"END_PROGRAM\n",
            fsms,
            sensors_referenced,
        )

    header = (
        f"(* Auto-generated by st_gen from {inp_filename} + {plcs_filename}\n"
        f"   Topology: {topology}   PLC: {plc.name}\n"
        f"   DO NOT EDIT. *)\n\n"
        f"PROGRAM {plc.name}\n"
    )
    if var_input_lines:
        header += "VAR_INPUT\n" + "\n".join(var_input_lines) + "\nEND_VAR\n"
    if output_decls:
        header += "VAR_OUTPUT\n" + "\n".join(output_decls) + "\nEND_VAR\n"
    if state_var_decls:
        header += "VAR\n" + "\n".join(state_var_decls) + "\nEND_VAR\n"
    body = "\n".join(case_blocks) + "\n"
    footer = "END_PROGRAM\n"
    return header + "\n" + body + footer, fsms, sensors_referenced


def _render_var_input_line(sensor: str, owner: dict[str, str], this_plc: str) -> str:
    if sensor not in owner:
        annot = "(* unassigned in plcs.yaml *)"
    elif owner[sensor] == this_plc:
        annot = "(* owned by this PLC *)"
    else:
        annot = f"(* sourced from {owner[sensor]} *)"
    sensor_id = _iec_ident(sensor)
    return f"    {sensor_id} : REAL;            {annot}"


def _render_case_block(
    actuator: str, ctrls: list[Control]
) -> tuple[str, dict, list[str]]:
    """Render one CASE block for a 2-state (OPEN/CLOSED) actuator.

    Raises MultiStateActuatorError if the same (comparator, threshold) pair maps
    to both OPEN and CLOSED — that is ambiguous and cannot be represented as a
    deterministic 2-state FSM.  Any number of distinct pairs is fine as long as
    each pair maps to exactly one target state.
    """
    pair_to_states: dict[tuple[str, float], set[str]] = {}
    for c in ctrls:
        key = (c.comparator, c.threshold)
        pair_to_states.setdefault(key, set()).add(c.target_state)
    ambiguous = {k: v for k, v in pair_to_states.items() if len(v) > 1}
    if ambiguous:
        raise MultiStateActuatorError(
            f"actuator {actuator!r} has ambiguous (comparator,threshold) pairs that map "
            f"to both OPEN and CLOSED: {ambiguous}"
        )

    open_trans = [c for c in ctrls if c.target_state == "OPEN"]
    closed_trans = [c for c in ctrls if c.target_state == "CLOSED"]

    act_id = _iec_ident(actuator)
    sensors: list[str] = []
    lines: list[str] = [f"(* ----- FSM for actuator {actuator} ----- *)"]
    lines.append(f"CASE {act_id}_State OF")

    # state 0 (CLOSED): transitions that flip to OPEN
    lines.append("    0:  (* CLOSED *)")
    for c in open_trans:
        sensors.append(c.sensor_node)
        op = "<" if c.comparator == "BELOW" else ">"
        sensor_id = _iec_ident(c.sensor_node)
        lines.append(f"        IF {sensor_id} {op} {c.threshold:g} THEN")
        lines.append(f"            {act_id}_State := 1;")
        lines.append("        END_IF;")

    # state 1 (OPEN): transitions that flip to CLOSED
    lines.append("    1:  (* OPEN *)")
    for c in closed_trans:
        sensors.append(c.sensor_node)
        op = "<" if c.comparator == "BELOW" else ">"
        sensor_id = _iec_ident(c.sensor_node)
        lines.append(f"        IF {sensor_id} {op} {c.threshold:g} THEN")
        lines.append(f"            {act_id}_State := 0;")
        lines.append("        END_IF;")

    lines.append("END_CASE;")
    lines.append(f"{act_id} := ({act_id}_State = 1);")
    block = "\n".join(lines) + "\n"
    fsm_meta = {
        "actuator": actuator,
        "states": 2,
        "transitions": len(open_trans) + len(closed_trans),
    }
    return block, fsm_meta, sensors
